
site_name: 'Terraform ECS Module'
site_description: 'Main documentation for Terraform ECS Module'
repo_url: https://github.com/toluna-terraform/terraform-aws-ecs
edit_uri: edit/master/docs

plugins:
  - techdocs-core

nav:
  - Terraform ECS Module: 'index.md'
